"""Persist sourced context and guide links for featured industry businesses."""
from pathlib import Path
import re

CONTEXT = {
    'common-plea-catering': ('Compare catering service levels', 'Common Plea separates full-service events from drop-off, delivery and pickup catering. Ask for staffing, setup, equipment and cleanup to be specified in your proposal. Contact 412-281-5140 or info@thecommonplea.com to confirm the event date and service scope.', 'https://www.thecommonplea.com/drop-off-catering', 'best-caterers-pittsburgh-editorial-picks'),
    'kindred-cycles': ('Plan a bicycle service enquiry', 'Kindred publishes separate intake instructions for flat fixes, tune-ups, boxing and custom builds. Confirm the estimate timing, parts approval and collection date before leaving a bicycle. Call 412-471-2656 or email kindredcycles@gmail.com.', 'https://www.kindredcycles.com/service', 'best-bike-repair-pittsburgh-editorial-picks'),
    'living-well-home-organizing': ('Prepare an organizing consultation', 'Living Well invites enquiries for a free consultation and publishes 610-349-2769 and livingwellservicespgh@gmail.com. Identify the rooms and transition tasks you need help with. Ask for a written scope separating labor, supplies and any transport arrangements.', 'https://www.livingwellservicespgh.com/services', 'best-home-organizers-pittsburgh-editorial-picks'),
    'expert-pest-management': ('Compare pest-control coverage', 'Separate a targeted visit from a recurring plan. Ask for the covered pests, assessment requirements, visit schedule and follow-up terms in writing before booking.', 'https://www.goexpertpest.com/pest-control-exterminator-pittsburgh/', 'best-pest-control-pittsburgh-editorial-picks'),
    'cw-electrical-services': ('Plan an electrical project enquiry', 'Identify the property type and the work required before requesting an estimate. CW publishes 412-766-1446 and info@cwelectricalservices.com. Confirm appointment availability, assessment charges and what the written proposal includes.', 'https://www.cwelectricalservices.com/', 'best-electricians-pittsburgh-editorial-picks'),
    'a-comfort-service': ('Current HVAC enquiry information', 'The official website currently lists 412-453-8538 for service enquiries. Identify the equipment and whether you need maintenance, diagnosis or replacement. Confirm address coverage, diagnostic charges and the appointment window directly.', 'https://www.acomfortservice.com/', 'best-hvac-companies-pittsburgh-editorial-picks'),
    'omex-office-maintenance-experts': ('Compare office cleaning scopes', 'OMEX lists office cleaning, restroom sanitation, carpet and tile-floor maintenance, window cleaning and porter service for Greater Pittsburgh. Identify recurring tasks and periodic work separately when requesting a quote. Confirm the property address and which services the local office can provide.', 'https://www.omexcorp.com/pittsburgh', 'best-commercial-cleaners-pittsburgh-editorial-picks'),
    'evolve-wellness-spa': ('Plan your spa appointment', 'Confirm the service, appointment length, deposit and cancellation terms before reserving. Multiple guests receive services in separate rooms. Discuss access needs directly: the spa says its building is not wheelchair accessible.', 'https://www.evolvewellnessspa.com/book-your-service', 'best-day-spas-pittsburgh-editorial-picks'),
    'local-roots-landscaping': ('Prepare a landscaping enquiry', 'Separate design, construction and recurring garden care in your brief. Confirm the property address, consultation charges and who handles maintenance after installation. Local Roots has a separate online maintenance appointment page.', 'https://www.localrootslandscaping.com/contact/contact-maintenance/', 'best-landscapers-pittsburgh-editorial-picks'),
    'resnick-roofing': ('Roofing and exterior project enquiries', 'Resnick lists roof repair, replacement, siding and gutter services. Its North Hills location is 5320 William Flynn Highway, Gibsonia, PA 15044; call 412-307-9809. The website limits its free-quote offer to full replacements, so confirm any repair assessment charge before booking.', 'https://www.resnickroof.com/', 'best-roofing-contractors-pittsburgh-editorial-picks'),
    '412-plumbing': ('Plan a plumbing enquiry', 'Confirm the service area, diagnostic charges and the scope of the first visit. Explain whether the property is residential or commercial and request a confirmed appointment window.', 'https://www.412plumbing.com/', 'best-plumbers-pittsburgh-editorial-picks'),
    'phipps-conservatory-and-botanical-gardens': ('Event planning at Phipps', 'Phipps lists garden and conservatory event settings and a separate Garden Center in Mellon Park. Its pricing page currently directs enquiries to the events team. Confirm the exact venue and request current terms.', 'https://www.phipps.conservatory.org/plan-your-event/', 'best-event-venues-pittsburgh-editorial-picks'),
    'baum-boulevard-automotive': ('Maintenance and diagnostic enquiries', 'Baum Boulevard Automotive publishes preventive maintenance, breakdown repair and diagnostics, with an online appointment option. Call 412-682-1866 to confirm the work and drop-off arrangements for your vehicle.', 'https://www.baumblvdauto.com/', 'best-auto-repair-pittsburgh-editorial-picks'),
    'union-fitness': ('Membership comparison', 'Compare the equipment-focused Fitness Center tier with UF Unlimited, which adds the full class schedule. Confirm access, class booking and current membership terms directly.', 'https://unionfitness.com/new-memberships/', 'best-gyms-pittsburgh-editorial-picks'),
    'south-hills-movers': ('Prepare a moving enquiry', 'Provide both addresses, the move date, inventory and access details. Request a written scope distinguishing transport, packing and any storage arrangements.', 'https://www.southhillsmovers.com/', 'best-moving-companies-pittsburgh-editorial-picks'),
}


def write(repo):
    for slug, (heading, detail, source, guide) in CONTEXT.items():
        page = Path(repo) / 'directory' / slug / 'index.html'
        markup = page.read_text()
        markup = re.sub(r'<!-- INDUSTRY_CONTEXT_START -->.*?<!-- INDUSTRY_CONTEXT_END -->', '', markup, flags=re.S)
        block = f'''<!-- INDUSTRY_CONTEXT_START --><section class="profile-copy"><h2>{heading}</h2><p>{detail}</p><p><a href="{source}" rel="noopener noreferrer">Official service information</a> · Checked October 10, 2026.</p><p>Featured in our <a href="/news/{guide}/">Pittsburgh industry comparison guide</a>. Inclusion is an editorial selection, not an independent award or a guarantee of service quality.</p></section><!-- INDUSTRY_CONTEXT_END -->'''
        assert '</main>' in markup
        page.write_text(markup.replace('</main>', block + '</main>', 1))
    return len(CONTEXT)
